// Generated by gencpp from file utils/dottedResponse.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_DOTTEDRESPONSE_H
#define UTILS_MESSAGE_DOTTEDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct dottedResponse_
{
  typedef dottedResponse_<ContainerAllocator> Type;

  dottedResponse_()
    : dotted(false)  {
    }
  dottedResponse_(const ContainerAllocator& _alloc)
    : dotted(false)  {
  (void)_alloc;
    }



   typedef uint8_t _dotted_type;
  _dotted_type dotted;





  typedef boost::shared_ptr< ::utils::dottedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::dottedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct dottedResponse_

typedef ::utils::dottedResponse_<std::allocator<void> > dottedResponse;

typedef boost::shared_ptr< ::utils::dottedResponse > dottedResponsePtr;
typedef boost::shared_ptr< ::utils::dottedResponse const> dottedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::dottedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::dottedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::dottedResponse_<ContainerAllocator1> & lhs, const ::utils::dottedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.dotted == rhs.dotted;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::dottedResponse_<ContainerAllocator1> & lhs, const ::utils::dottedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::dottedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::dottedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::dottedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::dottedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::dottedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::dottedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::dottedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c459471f396960cd81d365321f8af6f";
  }

  static const char* value(const ::utils::dottedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c459471f396960cULL;
  static const uint64_t static_value2 = 0xd81d365321f8af6fULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::dottedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/dottedResponse";
  }

  static const char* value(const ::utils::dottedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::dottedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool dotted\n"
;
  }

  static const char* value(const ::utils::dottedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::dottedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dotted);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dottedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::dottedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::dottedResponse_<ContainerAllocator>& v)
  {
    s << indent << "dotted: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dotted);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_DOTTEDRESPONSE_H
