// Generated by gencpp from file utils/dotted.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_DOTTED_H
#define UTILS_MESSAGE_DOTTED_H

#include <ros/service_traits.h>


#include <utils/dottedRequest.h>
#include <utils/dottedResponse.h>


namespace utils
{

struct dotted
{

typedef dottedRequest Request;
typedef dottedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct dotted
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::dotted > {
  static const char* value()
  {
    return "e314c20a3feea19c202c5fb6355f6614";
  }

  static const char* value(const ::utils::dotted&) { return value(); }
};

template<>
struct DataType< ::utils::dotted > {
  static const char* value()
  {
    return "utils/dotted";
  }

  static const char* value(const ::utils::dotted&) { return value(); }
};


// service_traits::MD5Sum< ::utils::dottedRequest> should match
// service_traits::MD5Sum< ::utils::dotted >
template<>
struct MD5Sum< ::utils::dottedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::dotted >::value();
  }
  static const char* value(const ::utils::dottedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::dottedRequest> should match
// service_traits::DataType< ::utils::dotted >
template<>
struct DataType< ::utils::dottedRequest>
{
  static const char* value()
  {
    return DataType< ::utils::dotted >::value();
  }
  static const char* value(const ::utils::dottedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::dottedResponse> should match
// service_traits::MD5Sum< ::utils::dotted >
template<>
struct MD5Sum< ::utils::dottedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::dotted >::value();
  }
  static const char* value(const ::utils::dottedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::dottedResponse> should match
// service_traits::DataType< ::utils::dotted >
template<>
struct DataType< ::utils::dottedResponse>
{
  static const char* value()
  {
    return DataType< ::utils::dotted >::value();
  }
  static const char* value(const ::utils::dottedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_DOTTED_H
