// Generated by gencpp from file utils/get_directionRequest.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GET_DIRECTIONREQUEST_H
#define UTILS_MESSAGE_GET_DIRECTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct get_directionRequest_
{
  typedef get_directionRequest_<ContainerAllocator> Type;

  get_directionRequest_()
    : x(0.0)
    , y(0.0)
    , r(0.0)
    , dest()  {
    }
  get_directionRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , r(0.0)
    , dest(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _r_type;
  _r_type r;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dest_type;
  _dest_type dest;





  typedef boost::shared_ptr< ::utils::get_directionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::get_directionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct get_directionRequest_

typedef ::utils::get_directionRequest_<std::allocator<void> > get_directionRequest;

typedef boost::shared_ptr< ::utils::get_directionRequest > get_directionRequestPtr;
typedef boost::shared_ptr< ::utils::get_directionRequest const> get_directionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::get_directionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::get_directionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::get_directionRequest_<ContainerAllocator1> & lhs, const ::utils::get_directionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.r == rhs.r &&
    lhs.dest == rhs.dest;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::get_directionRequest_<ContainerAllocator1> & lhs, const ::utils::get_directionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::get_directionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::get_directionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::get_directionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::get_directionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::get_directionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::get_directionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::get_directionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99419778a8ff692a4e0cfbb75cc8fbf4";
  }

  static const char* value(const ::utils::get_directionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99419778a8ff692aULL;
  static const uint64_t static_value2 = 0x4e0cfbb75cc8fbf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::get_directionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/get_directionRequest";
  }

  static const char* value(const ::utils::get_directionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::get_directionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 r\n"
"string dest\n"
;
  }

  static const char* value(const ::utils::get_directionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::get_directionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.r);
      stream.next(m.dest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_directionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::get_directionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::get_directionRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "r: ";
    Printer<float>::stream(s, indent + "  ", v.r);
    s << indent << "dest: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dest);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_GET_DIRECTIONREQUEST_H
