// Generated by gencpp from file utils/get_direction.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_GET_DIRECTION_H
#define UTILS_MESSAGE_GET_DIRECTION_H

#include <ros/service_traits.h>


#include <utils/get_directionRequest.h>
#include <utils/get_directionResponse.h>


namespace utils
{

struct get_direction
{

typedef get_directionRequest Request;
typedef get_directionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_direction
} // namespace utils


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::utils::get_direction > {
  static const char* value()
  {
    return "e06bd54dc49cad3c7c3e45a6cc5ec3c7";
  }

  static const char* value(const ::utils::get_direction&) { return value(); }
};

template<>
struct DataType< ::utils::get_direction > {
  static const char* value()
  {
    return "utils/get_direction";
  }

  static const char* value(const ::utils::get_direction&) { return value(); }
};


// service_traits::MD5Sum< ::utils::get_directionRequest> should match
// service_traits::MD5Sum< ::utils::get_direction >
template<>
struct MD5Sum< ::utils::get_directionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::utils::get_direction >::value();
  }
  static const char* value(const ::utils::get_directionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::get_directionRequest> should match
// service_traits::DataType< ::utils::get_direction >
template<>
struct DataType< ::utils::get_directionRequest>
{
  static const char* value()
  {
    return DataType< ::utils::get_direction >::value();
  }
  static const char* value(const ::utils::get_directionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::utils::get_directionResponse> should match
// service_traits::MD5Sum< ::utils::get_direction >
template<>
struct MD5Sum< ::utils::get_directionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::utils::get_direction >::value();
  }
  static const char* value(const ::utils::get_directionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::utils::get_directionResponse> should match
// service_traits::DataType< ::utils::get_direction >
template<>
struct DataType< ::utils::get_directionResponse>
{
  static const char* value()
  {
    return DataType< ::utils::get_direction >::value();
  }
  static const char* value(const ::utils::get_directionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UTILS_MESSAGE_GET_DIRECTION_H
