// Generated by gencpp from file utils/Lane.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_LANE_H
#define UTILS_MESSAGE_LANE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct Lane_
{
  typedef Lane_<ContainerAllocator> Type;

  Lane_()
    : header()
    , center(0.0)
    , stopline(false)  {
    }
  Lane_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , center(0.0)
    , stopline(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _center_type;
  _center_type center;

   typedef uint8_t _stopline_type;
  _stopline_type stopline;





  typedef boost::shared_ptr< ::utils::Lane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::Lane_<ContainerAllocator> const> ConstPtr;

}; // struct Lane_

typedef ::utils::Lane_<std::allocator<void> > Lane;

typedef boost::shared_ptr< ::utils::Lane > LanePtr;
typedef boost::shared_ptr< ::utils::Lane const> LaneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::Lane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::Lane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::Lane_<ContainerAllocator1> & lhs, const ::utils::Lane_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.center == rhs.center &&
    lhs.stopline == rhs.stopline;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::Lane_<ContainerAllocator1> & lhs, const ::utils::Lane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::Lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::Lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::Lane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::Lane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Lane_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "708d34d457396320a4fc95f395fc6042";
  }

  static const char* value(const ::utils::Lane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x708d34d457396320ULL;
  static const uint64_t static_value2 = 0xa4fc95f395fc6042ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/Lane";
  }

  static const char* value(const ::utils::Lane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::Lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"float32 center\n"
"bool stopline\n"
"# bool dotted\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::Lane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::Lane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.center);
      stream.next(m.stopline);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::Lane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::Lane_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "center: ";
    Printer<float>::stream(s, indent + "  ", v.center);
    s << indent << "stopline: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stopline);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_LANE_H
