// Generated by gencpp from file utils/navRequest.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_NAVREQUEST_H
#define UTILS_MESSAGE_NAVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct navRequest_
{
  typedef navRequest_<ContainerAllocator> Type;

  navRequest_()
    : speed(0.0)
    , steering(0.0)
    , time(0.0)  {
    }
  navRequest_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , steering(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef float _speed_type;
  _speed_type speed;

   typedef float _steering_type;
  _steering_type steering;

   typedef float _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::utils::navRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::navRequest_<ContainerAllocator> const> ConstPtr;

}; // struct navRequest_

typedef ::utils::navRequest_<std::allocator<void> > navRequest;

typedef boost::shared_ptr< ::utils::navRequest > navRequestPtr;
typedef boost::shared_ptr< ::utils::navRequest const> navRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::navRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::navRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::navRequest_<ContainerAllocator1> & lhs, const ::utils::navRequest_<ContainerAllocator2> & rhs)
{
  return lhs.speed == rhs.speed &&
    lhs.steering == rhs.steering &&
    lhs.time == rhs.time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::navRequest_<ContainerAllocator1> & lhs, const ::utils::navRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::navRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::navRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::navRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::navRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::navRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::navRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::navRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a85f004a44122766ad25e75dc789c7bd";
  }

  static const char* value(const ::utils::navRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa85f004a44122766ULL;
  static const uint64_t static_value2 = 0xad25e75dc789c7bdULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::navRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/navRequest";
  }

  static const char* value(const ::utils::navRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::navRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 speed\n"
"float32 steering\n"
"float32 time\n"
;
  }

  static const char* value(const ::utils::navRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::navRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.steering);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct navRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::navRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::navRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_NAVREQUEST_H
