// Generated by gencpp from file utils/navResponse.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_NAVRESPONSE_H
#define UTILS_MESSAGE_NAVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct navResponse_
{
  typedef navResponse_<ContainerAllocator> Type;

  navResponse_()
    : dir()  {
    }
  navResponse_(const ContainerAllocator& _alloc)
    : dir(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _dir_type;
  _dir_type dir;





  typedef boost::shared_ptr< ::utils::navResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::navResponse_<ContainerAllocator> const> ConstPtr;

}; // struct navResponse_

typedef ::utils::navResponse_<std::allocator<void> > navResponse;

typedef boost::shared_ptr< ::utils::navResponse > navResponsePtr;
typedef boost::shared_ptr< ::utils::navResponse const> navResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::navResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::navResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::navResponse_<ContainerAllocator1> & lhs, const ::utils::navResponse_<ContainerAllocator2> & rhs)
{
  return lhs.dir == rhs.dir;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::navResponse_<ContainerAllocator1> & lhs, const ::utils::navResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::navResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::navResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::navResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::navResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::navResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::navResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62d9ed94d8c9bfb0d09360128fec1033";
  }

  static const char* value(const ::utils::navResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62d9ed94d8c9bfb0ULL;
  static const uint64_t static_value2 = 0xd09360128fec1033ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/navResponse";
  }

  static const char* value(const ::utils::navResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string dir\n"
;
  }

  static const char* value(const ::utils::navResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::navResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct navResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::navResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::navResponse_<ContainerAllocator>& v)
  {
    s << indent << "dir: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_NAVRESPONSE_H
