// Generated by gencpp from file utils/odometry.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_ODOMETRY_H
#define UTILS_MESSAGE_ODOMETRY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace utils
{
template <class ContainerAllocator>
struct odometry_
{
  typedef odometry_<ContainerAllocator> Type;

  odometry_()
    : header()
    , odomX(0.0)
    , odomY(0.0)
    , odomYaw(0.0)  {
    }
  odometry_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , odomX(0.0)
    , odomY(0.0)
    , odomYaw(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _odomX_type;
  _odomX_type odomX;

   typedef float _odomY_type;
  _odomY_type odomY;

   typedef float _odomYaw_type;
  _odomYaw_type odomYaw;





  typedef boost::shared_ptr< ::utils::odometry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::odometry_<ContainerAllocator> const> ConstPtr;

}; // struct odometry_

typedef ::utils::odometry_<std::allocator<void> > odometry;

typedef boost::shared_ptr< ::utils::odometry > odometryPtr;
typedef boost::shared_ptr< ::utils::odometry const> odometryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::odometry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::odometry_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::odometry_<ContainerAllocator1> & lhs, const ::utils::odometry_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.odomX == rhs.odomX &&
    lhs.odomY == rhs.odomY &&
    lhs.odomYaw == rhs.odomYaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::odometry_<ContainerAllocator1> & lhs, const ::utils::odometry_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::odometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::odometry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::odometry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::odometry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::odometry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::odometry_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::odometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a51da1ea6b66db5cbffc01f7341d40f";
  }

  static const char* value(const ::utils::odometry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a51da1ea6b66db5ULL;
  static const uint64_t static_value2 = 0xcbffc01f7341d40fULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::odometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/odometry";
  }

  static const char* value(const ::utils::odometry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::odometry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 odomX\n"
"float32 odomY\n"
"float32 odomYaw\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::utils::odometry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::odometry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.odomX);
      stream.next(m.odomY);
      stream.next(m.odomYaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct odometry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::odometry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::odometry_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "odomX: ";
    Printer<float>::stream(s, indent + "  ", v.odomX);
    s << indent << "odomY: ";
    Printer<float>::stream(s, indent + "  ", v.odomY);
    s << indent << "odomYaw: ";
    Printer<float>::stream(s, indent + "  ", v.odomYaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_ODOMETRY_H
