// Generated by gencpp from file utils/Sensors.msg
// DO NOT EDIT!


#ifndef UTILS_MESSAGE_SENSORS_H
#define UTILS_MESSAGE_SENSORS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace utils
{
template <class ContainerAllocator>
struct Sensors_
{
  typedef Sensors_<ContainerAllocator> Type;

  Sensors_()
    : yaw(0.0)
    , speed(0.0)  {
    }
  Sensors_(const ContainerAllocator& _alloc)
    : yaw(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::utils::Sensors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::utils::Sensors_<ContainerAllocator> const> ConstPtr;

}; // struct Sensors_

typedef ::utils::Sensors_<std::allocator<void> > Sensors;

typedef boost::shared_ptr< ::utils::Sensors > SensorsPtr;
typedef boost::shared_ptr< ::utils::Sensors const> SensorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::utils::Sensors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::utils::Sensors_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::utils::Sensors_<ContainerAllocator1> & lhs, const ::utils::Sensors_<ContainerAllocator2> & rhs)
{
  return lhs.yaw == rhs.yaw &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::utils::Sensors_<ContainerAllocator1> & lhs, const ::utils::Sensors_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace utils

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::utils::Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::utils::Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::Sensors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::utils::Sensors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Sensors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::utils::Sensors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::utils::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0708b47c61ea53e7faa2ee55ab9e77b7";
  }

  static const char* value(const ::utils::Sensors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0708b47c61ea53e7ULL;
  static const uint64_t static_value2 = 0xfaa2ee55ab9e77b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::utils::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "utils/Sensors";
  }

  static const char* value(const ::utils::Sensors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::utils::Sensors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 yaw\n"
"float32 speed\n"
;
  }

  static const char* value(const ::utils::Sensors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::utils::Sensors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Sensors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::utils::Sensors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::utils::Sensors_<ContainerAllocator>& v)
  {
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UTILS_MESSAGE_SENSORS_H
