<robot name="amy" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- <xacro:property name="PI" value="3.1415927" /> -->
    <xacro:property name="footprint_r" value="0.001" />
    <link name="base_footprint">
        <visual>
            <geometry>
                <box size="${footprint_r} ${footprint_r} ${footprint_r}" />
            </geometry>
        </visual>
    </link>

    <xacro:property name="base_radius" value="0.1" />
    <xacro:property name="base_length" value="0.0375" />
    <xacro:property name="base_mass" value="2" />
    <xacro:property name="lidi" value="0.015" />
    <xacro:property name="base_joint_z" value="${base_length/2+lidi}" />
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="base_link_color">
                <color rgba="1.0 0.5 0.2 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertial_matrix m="${base_mass}" r="${base_radius}" h="${base_length}"/>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>
    <joint name="link2footprint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_joint_z}" rpy="0 0 0"/>
    </joint>

    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_joint_z" value="${-base_length/2-lidi+wheel_radius}" />
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
                <material name="wheel_color">
                    <color rgba="1 1 1 1" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
        </link>
        <gazebo reference = "${wheel_name}_wheel" >
            <material>Gazebo/White</material>
        </gazebo>
        <joint name="${wheel_name}2link" type="continuous">
            <parent link="base_link"/>
            <child link="${wheel_name}_wheel"/>
            <origin xyz="0 ${0.1*flag} ${wheel_joint_z}" rpy="0 0 0"/>
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />

    <xacro:property name="small_wheel_r" value="0.0075" />
    <xacro:property name="small_wheel_mass" value="0.01" />
    <xacro:property name="small_joint_z" value="${(base_length/2+lidi-small_wheel_r)*-1}" />
    <xacro:macro name="small_wheel_func" params="small_w flag" >
        <link name="${small_w}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${small_wheel_r}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="wheel_color">
                    <color rgba="0 0 0 1" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${small_wheel_r}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertial_matrix m="${small_wheel_mass}" r="${small_wheel_r}" />
        </link>
        <gazebo reference = "${small_w}_wheel" >
            <material>Gazebo/Red</material>
        </gazebo>
        <joint name="${small_w}2link" type="continuous">
            <parent link="base_link"/>
            <child link="${small_w}_wheel"/>
            <origin xyz="${0.08*flag} 0 ${small_joint_z}" rpy="0 0 0"/>
            <axis xyz="1 1 1" />
        </joint>
    </xacro:macro>
    <xacro:small_wheel_func small_w="front" flag="1" />
    <xacro:small_wheel_func small_w="back" flag="-1" />
</robot>