(cl:defpackage utils-srv
  (:use )
  (:export
   "LOCALIZATION"
   "<LOCALIZATION-REQUEST>"
   "LOCALIZATION-REQUEST"
   "<LOCALIZATION-RESPONSE>"
   "LOCALIZATION-RESPONSE"
   "DOTTED"
   "<DOTTED-REQUEST>"
   "DOTTED-REQUEST"
   "<DOTTED-RESPONSE>"
   "DOTTED-RESPONSE"
   "GET_DIRECTION"
   "<GET_DIRECTION-REQUEST>"
   "GET_DIRECTION-REQUEST"
   "<GET_DIRECTION-RESPONSE>"
   "GET_DIRECTION-RESPONSE"
   "NAV"
   "<NAV-REQUEST>"
   "NAV-REQUEST"
   "<NAV-RESPONSE>"
   "NAV-RESPONSE"
  ))

