# Request part string for name 
string pathName
string vrefName
---
# Response part
std_msgs/Float32MultiArray state_refs
std_msgs/Float32MultiArray input_refs
std_msgs/Float32MultiArray wp_attributes
std_msgs/Float32MultiArray wp_normals
